# Generated by Django 5.2.6 on 2025-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_admin_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_duration_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'borrow_record_table',
            },
        ),
    ]
