# Generated by Django 5.2.6 on 2025-09-24 09:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_issuedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('DinaThanthi', 'Dina Thanthi'), ('Dinamalar', 'Dina Malar'), ('TheHindu', 'The Hindu'), ('IndianExpress', 'Indian Express'), ('Dinamani', 'Dina Mani')], max_length=50)),
                ('language', models.CharField(choices=[('TA', 'Tamil'), ('EN', 'English')], max_length=20)),
                ('publish_date', models.DateField(default=builtins.pow)),
                ('file', models.FileField(upload_to='newspapers/')),
            ],
        ),
    ]
