# Generated by Django 5.2.6 on 2025-09-24 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_newspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
