# Generated by Django 5.2.6 on 2025-09-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
