# Generated by Django 5.2.6 on 2025-09-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_purchaserequest_staff_staffmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_exam',
            },
        ),
        migrations.CreateModel(
            name='SubExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subexams', to='myapp.mainexam')),
            ],
            options={
                'db_table': 'sub_exam',
            },
        ),
    ]
