# Generated by Django 5.2.6 on 2025-10-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_mainexam_subexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.staffuser'),
        ),
    ]
