# Generated by Django 5.2.6 on 2025-10-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_purchaserequest_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmessage',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffuser'),
        ),
    ]
